version: "3"

name: "sosiny-tester"

services:
  test_db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test1234
      - POSTGRES_DB=test_db
    volumes:
      - ./db/init/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user"]
      interval: 6s
      retries: 5

  test_runner:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      test_db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://test:test1234@test_db:5432/test_db
