version: "3"

name: "sosiny-tester"

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test1234
      - POSTGRES_DB=test_db
    volumes:
      - ./db/init/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test"]
      interval: 6s
      retries: 5

  tester:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://test:test1234@db:5432/test_db
      - JWT_ACCESS=test_access
      - JWT_REFRESH=test_refresh
