version: "3"

name: "sosiny"

services:
  db:
    image: postgres:latest
    env_file: .env.db
    restart: always
    volumes:
      # - ./db/data/:/var/lib/postgresql/data/
      - ./db/init/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sosiny"]
      interval: 6s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
